
--ON PREMISES LOGS

CREATE TABLE sales.PIPELINELOGS_ONPREMISES
(
ID INT IDENTITY(1,1),
TABLENAME VARCHAR(100),
SCHEMANAME VARCHAR(100),
ROWREAD BIGINT,
ROWCOPIED BIGINT,
ERRORMESSAGE VARCHAR(500),
COPYDURATION BIGINT,
LOGTIME DATETIME
)


CREATE PROC USP_LOGDETAILS_ONPREMISES
@TABLENAME VARCHAR(100),
@SCHEMANAME VARCHAR(100),
@ROWREAD BIGINT,
@ROWCOPIED BIGINT,
@ERRORMESSAGE VARCHAR(500),
@COPYDURATION BIGINT,
@LOGTIME DATETIME
AS
INSERT INTO sales.PIPELINELOGS_ONPREMISES VALUES
(
@TABLENAME ,
@SCHEMANAME ,
@ROWREAD ,
@ROWCOPIED,
@ERRORMESSAGE,
@COPYDURATION,
@LOGTIME
)

SELECT * FROM sales.PIPELINELOGS_ONPREMISES

drop table sales.PIPELINELOGS_ONPREMISES
drop PROC USP_LOGDETAILS_ONPREMISES


--REST API LOGS

CREATE TABLE sales.PIPELINELOGS_RESTAPI
(
ID INT IDENTITY(1,1),
TABLENAME VARCHAR(100),
ROWREAD BIGINT,
ROWCOPIED BIGINT,
ERRORMESSAGE VARCHAR(500),
COPYDURATION BIGINT,
LOGTIME DATETIME
)


CREATE PROC USP_LOGDETAILS_RESTAPI
@TABLENAME VARCHAR(100),
@ROWREAD BIGINT,
@ROWCOPIED BIGINT,
@ERRORMESSAGE VARCHAR(500),
@COPYDURATION BIGINT,
@LOGTIME DATETIME
AS
INSERT INTO sales.PIPELINELOGS_RESTAPI VALUES
(
@TABLENAME ,
@ROWREAD ,
@ROWCOPIED,
@ERRORMESSAGE,
@COPYDURATION,
@LOGTIME
)

SELECT * FROM sales.PIPELINELOGS_RESTAPI

drop proc USP_LOGDETAILS_RESTAPI
drop table sales.PIPELINELOGS_RESTAPI




-- Create Watermark Table
CREATE TABLE sales.WATERMARKTABLE
(
    ID INT IDENTITY(1,1),
    TABLENAME VARCHAR(100),
    SCHEMANAME VARCHAR(100),
    FOLDERNAME VARCHAR(100),
    FILENAME VARCHAR(150),
    DELTACOL VARCHAR(100),
    LASTPROCESSEDVALUE DATETIME
);


INSERT INTO sales.WATERMARKTABLE
(TABLENAME, SCHEMANAME, FOLDERNAME, FILENAME, DELTACOL, LASTPROCESSEDVALUE)
VALUES
('Customers',     'sales', 'customers',     'customers.csv',     'ModifiedDate', '1900-01-01 00:00:00'),
('Products',      'sales', 'products',      'products.csv',      'ModifiedDate', '1900-01-01 00:00:00'),
('Stores',        'sales', 'stores',        'stores.csv',        'ModifiedDate', '1900-01-01 00:00:00'),
('Orders',        'sales', 'orders',        'orders.csv',        'ModifiedDate', '1900-01-01 00:00:00'),
('OrderDetails',  'sales', 'orderdetails',  'orderdetails.csv',  'ModifiedDate', '1900-01-01 00:00:00');

select * from sales.WATERMARKTABLE



create proc sales.usp_updatewatermarktable1
@tablename varchar(100),
@lpv varchar(100)
as
update sales.WATERMARKTABLE
set LASTPROCESSEDVALUE=@lpv
where TABLENAME=@tablename


drop table sales.WATERMARKTABLE

