name: ADF CI/CD Pipeline

on:
  push:
    branches:
      - main
      - test
      - prod

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Checkout adf_publish
        uses: actions/checkout@v3
        with:
          ref: adf_publish
          path: adf_publish

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: >
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Deploy DEV
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ secrets.AZURE_RG_DEV }}
          template: ./adf_publish/adfprojectdemo123/ARMTemplateForFactory.json
          parameters: >
            ./adf_publish/adfprojectdemo123/ARMTemplateParametersForFactory.json
            factoryName=adfprojectdemo123
          deploymentName: adf-dev-deployment


  deploy-test:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Checkout adf_publish
        uses: actions/checkout@v3
        with:
          ref: adf_publish
          path: adf_publish

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: >
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Deploy TEST
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ secrets.AZURE_RG_TEST }}
          template: ./adf_publish/adfprojectdemo123/ARMTemplateForFactory.json
          parameters: >
            ./adf_publish/adfprojectdemo123/ARMTemplateParametersForFactory.json
            factoryName=adfprojectdemo123
          deploymentName: adf-test-deployment


  deploy-prod:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Checkout adf_publish
        uses: actions/checkout@v3
        with:
          ref: adf_publish
          path: adf_publish

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: >
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Deploy PROD
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ secrets.AZURE_RG_PROD }}
          template: ./adf_publish/adfprojectdemo123/ARMTemplateForFactory.json
          parameters: >
            ./adf_publish/adfprojectdemo123/ARMTemplateParametersForFactory.json
            factoryName=adfprojectdemo123
          deploymentName: adf-prod-deployment
