name: ADF CI/CD Pipeline

on:
  push:
    branches:
      - main
      - test
      - prod

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Deploy DEV
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ secrets.AZURE_RG_DEV }}
          template: ./adf_publish/adfprojectdemo123/ARMTemplateForFactory.json
          parameters: >
            ./adf_publish/adfprojectdemo123/ARMTemplateParametersForFactory.json
            factoryName=adf-dev-dharmil
          deploymentName: adf-dev-deployment


  deploy-test:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Deploy TEST
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ secrets.AZURE_RG_TEST }}
          template: ./adf_publish/adfprojectdemo123/ARMTemplateForFactory.json
          parameters: >
            ./adf_publish/adfprojectdemo123/ARMTemplateParametersForFactory.json
            factoryName=adf-test-dharmil
          deploymentName: adf-test-deployment


  deploy-prod:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Deploy PROD
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ secrets.AZURE_RG_PROD }}
          template: ./adf_publish/adfprojectdemo123/ARMTemplateForFactory.json
          parameters: >
            ./adf_publish/adfprojectdemo123/ARMTemplateParametersForFactory.json
            factoryName=adf-prod-dharmil
          deploymentName: adf-prod-deployment
